### ISSUE TITLE
Generating demo content

### ISSUE THREAD

**Issue by ugintl** [singularo/stratoserp_base#10]
Is it possible to generate demo content? I enabled "testing" module, but nothing happened.

**Comment by singularo** [comment]
The testing module is for phpunit tests.
There should be some service items generated during the installation via the item installation - https://github.com/stratoserp/stratoserp/blob/develop/modules/se_item/se_item.install
There are no businesses generated at the moment, that could be nicer, adding a demo content module should be one of the options. Will leave this open and update with that.

**Comment by singularo** [comment]
https://github.com/stratoserp/stratoserp/tree/develop/modules/se_example_data is now used for this task and installed as part of the test suite.
