### ISSUE TITLE
Some changes would make it more adoptable and easier for community

### ISSUE THREAD

**Issue by ugintl** [singularo/stratoserp_base#14]
Can you please move "ext-posix" and "singularo/shepherd-drupal-scaffold" from require to suggest? When I try to download from composer template, It does not download because I do not have ext-posix. I think it will become more adoptable if you can make it easier for people to download and install.

**Comment by singularo** [comment]
posix requirement removed, composer install on windows now works, well it fails later on the patch command instead, actually.
The solution to this is to:
- install git for windows from https://git-scm.com
- Right click on start
- Choose system
- Choose Advanced system settings
- Choose Environment variables
- Highlight Path in the bottom section and click edit
- Click New and add C:\Program Files\Git\usr\bin to the path
- Reboot

Then composer install works with:
```
composer create-project stratoserp/stratos-drupal-project:dev-develop test --stability dev --no-interaction
```
