### ISSUE TITLE
se_business is missing

### ISSUE THREAD

**Issue by frank2333** [singularo/stratoserp_base#4]
Hi Singularo,

There is a required module named se_business in stratoserp_base.info.yml, but seems I can not find it in https://github.com/stratoserp/stratoserp, is it missing?

Thanks.
Frank

**Comment by singularo** [comment]
Hey @frank2333 I have a big update to push to the https://github.com/stratoserp/stratoserp repository in the next few days, which will resolve this. I'll update here again once that is done.

**Comment by ugintl** [comment]
Waiting for the update

**Comment by singularo** [comment]
Should be sorted now.
