### ISSUE TITLE
What do you recommend

### ISSUE THREAD

**Issue by ugintl** [singularo/stratoserp_base#7]
I see you recommend profile over stratoserp module. Why?

Let us say I have an existing site and I want to integrate erp features into the site. What should I do?

If I use stratoserp profile, I have to implement all the design I want on it again. It should be easier to integrate into existing site.

**Comment by singularo** [comment]
I don't mind either way, but If you use the profile, or just take hints from the profile, then it will be easier to ensure that the requirements are there.

I'm not sure what you are trying to do, but this module set isn't really built to be part of a user facing site, but more as a way to run and bill a small business.
